services:
  - type: web
    name: siket-ekub-webapp
    runtime: python
    region: singapore
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      # ====== REQUIRED ======
      - key: BOT_TOKEN
        value: 8929371440:AAH7DFvko6YC98FtImSsgvVWn_Kqcl3pDRk
      - key: ADMIN_IDS
        value: "699428281,1029660827"
            - key: PORT
        value: "10000"
      - key: DASHBOARD_PORT
        value: "10001"
      - key: WEB_CONCURRENCY
        value: "1"
      # ====== PYTHON VERSION ======
      - key: PYTHON_VERSION
        value: 3.12.0
      
      # ====== DATABASE ======
      - key: DATABASE_URL
        value: postgresql://siket_ekub_db_87tt_user:TctsaN6ZxJZK3jdyV9xrgM3kwsRpBK9u@dpg-da7b410u01pc738r4tt0-a/siket_ekub_db_87tt
        # ← Your Render PostgreSQL URL
      
      # ====== WEBAPP URL ======
      - key: WEBAPP_URL
        value: https://siket-ekub-webapp.onrender.com
      
      # ====== CHANNELS ======
      - key: SUPPORT_CHANNEL_LINK
        value: https://t.me/siketekub
      - key: SUPPORT_CHANNEL_ID
        value: @siketekub
      - key: TICKET_CHANNEL_LINK
        value: https://t.me/siketekubtiketo
      - key: TICKET_CHANNEL_ID
        value: @siketekubtiketo
